### PR TITLE
Add ubuntu 14.10 to supported versions (#35)

### PR DESCRIPTION
**Pull request by cosmin-malutan**
This is for issue #35

### CODE REVIEW

**Comment by whimboo** [comment]
Why has this never gotten a review before it landed? cc'ing @andreeamatei .

**Comment by cosmin-malutan** [comment]
No one was around so I asked @lizzard to check the page. https://github.com/mozilla/mciconf/issues/35

**Comment by whimboo** [comment]
This is not an excuse to get code landed! There was a working test page she could have used for her testing.

**Comment by lizzard** [comment]
Did I do something wrong here? Cosmin asked me to check his change on a test page at http://cosmin-malutan.github.io/mciconf/app/ on Dec. 30th, I had a look at it, and let him know that it looked ok.

**Comment by whimboo** [comment]
No, you didn't something wrong. It's just that this PR has been merged without proper review from a peer.

**Comment by cosmin-malutan** [comment]
I'm sorry for any trouble here, I felt confident enough in changing some values in this json file, and definitely I didn't had anything to gain, I was just trying to help.

**Pull request closed without merging**
